# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Greg Lilley
description: I'm a designer focused on UI and UX. This portfolio contains recent work for Huitly, Native Canadian Ministries, and 3 Dollar Monsters. I'm currently available for hire. 
tagline: Design Portfolio
url: http://www.gregllly.com/blog/

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.owner.name' and so on
owner:
  name: glilley
  email: gregrlilley@gmail.com
  bio: Desinger
  twitter: http://www.twitter.com/gregllly

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink: pretty
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['smart']
pygments: true
